name: Lint, Tests and Upload Image

on:
  push:
    branches: [ master, release* ]

jobs:

  tests-and-upload-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    #Check caching for python dependencies to speed up process
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build, tag, and push image to Amazon ECR
      if: github.event.label.name == "build" && true
      env:
        IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
      run: |
        echo "Test"
        echo ${IMAGE_TAG} 
