name: Lint, Tests and Upload Image

on:
  push:
    branches: [ master, release* ]

jobs:

  tests-and-upload-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    #Check caching for python dependencies to speed up process
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: leela-server-branch
        IMAGE_TAG: ${{ github.head_ref }}
      run: |
        echo ${ECR_REPOSITORY}
        echo ${IMAGE_TAG##*/} .
        docker build --build-arg  -t reg/repo:${IMAGE_TAG##*/} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG##*/}
