name: Lint, Tests and Upload Image

on:
  pull_request:
    branches: [ master, release* ]

jobs:

  tests-and-upload-image:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build, tag, and push image to Amazon ECR
      if: contains(github.event.label.name, 'build' )
      env:
        IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
      run: |
        echo "Test"
        echo ${IMAGE_TAG} 
